#!/bin/bash
set -e

# Configuration
REGION="us-east-1"
PATH_PREFIX="/shortix/prod/"
ENV_FILE=".env"

echo "🔍 Syncing environment variables from AWS SSM Parameter Store ($REGION)..."

# Fetch all parameters under the path
# Error handling: if no parameters are found, PARAMS will be empty
PARAMS=$(aws ssm get-parameters-by-path \
    --path "$PATH_PREFIX" \
    --recursive \
    --region "$REGION" \
    --query "Parameters[*].{Name:Name,Value:Value}" \
    --output json)

if [ "$PARAMS" == "[]" ] || [ -z "$PARAMS" ]; then
    echo "❌ Error: No parameters found under $PATH_PREFIX in $REGION"
    exit 1
fi

# Create/Overwrite .env file
echo "# Generated by sync-env.sh on $(date)" > "$ENV_FILE"
echo "# Source: AWS SSM Parameter Store ($PATH_PREFIX)" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Function to add parameter to .env
# Usage: add_to_env <ssm_suffix> <env_name>
function add_to_env() {
    local ssm_suffix=$1
    local env_name=$2
    local full_path="$PATH_PREFIX$ssm_suffix"
    
    # Extract value using jq
    local value=$(echo "$PARAMS" | jq -r ".[] | select(.Name==\"$full_path\") | .Value")
    
    if [ ! -z "$value" ] && [ "$value" != "null" ]; then
        echo "$env_name=$value" >> "$ENV_FILE"
        echo "✅ Added $env_name"
    else
        echo "⚠️  Warning: Parameter $full_path not found"
    fi
}

# Mapping SSM hierarchy to VITE_ environment variables
add_to_env "auth/user-pool-id" "VITE_USER_POOL_ID"
add_to_env "auth/client-id" "VITE_CLIENT_ID"
add_to_env "api/url" "VITE_API_URL"

echo ""
echo "✨ Done! Environment synchronization complete."
echo "📝 Created $ENV_FILE"
